[package]
name = "flume2" # !!!!!!!!!!!!!!!!!!!!!! CHANGE NAME !!!!!!!!!!!!!!!!!!!!!!
version = "0.10.1"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
description = "A blazingly fast multi-producer channel"
repository = "https://github.com/zesterer/flume"
keywords = ["mpsc", "fifo", "channel", "thread", "fast"]
categories = ["concurrency", "data-structures"]
license = "Apache-2.0/MIT"
readme = "README.md"
exclude = [
	"/.github",
	"/misc",
]

[features]
default = ["std", "sync"]
# Support for `futures::Stream`
stream = []
# Support for `futures::Sink`
sink = ["futures-sink"]
# Standard library support (better thread contention performance)
std = []
# Synchronous channel operations like `.send(x)` and `.recv()`
sync = ["std", "pollster"]
# Synchronous timeout and deadline operations
time = ["sync", "futures-timer", "futures-util"]
# Support for the `select!` macro and selection
select = ["std", "futures-util/alloc"]

[dependencies]
spin = "0.7"
pin-project-lite = "0.2"
futures-core = "0.3"
futures-sink = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true }
futures-timer = { version = "3.0", optional = true }
pollster = { version = "0.2", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dev-dependencies]
crossbeam-channel = "0.4"
crossbeam-utils = "0.7"
criterion = "0.3.1"
rand = "0.7"
async-std = { version = "1.5", features = ["attributes", "unstable"] }
futures = { version = "^0.3", features = ["std"] }
waker-fn = "1.1.0"

[[bench]]
name = "basic"
harness = false
