[package]
name = "flume"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
description = "A blazingly fast multi-producer channel"

[dependencies]
spin = "0.5"
deque = "0.3"

[dev-dependencies]
crossbeam-channel = "0.3"
criterion = "0.2"

[profile.release]
debug = true

[[bench]]
name = "basic"
harness = false
