[package]
name = "flume"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
description = "A blazingly fast multi-producer channel"
repository = "https://github.com/zesterer/flume"
keywords = ["mpsc", "fifo", "channel", "thread", "fast"]
categories = ["concurrency", "data-structures"]
license = "Apache-2.0/MIT"
readme = "README.md"

[dependencies]
spin = "0.5"
spin_sleep = "0.3"

[dev-dependencies]
crossbeam-channel = "0.3"
criterion = "0.2"

[profile.release]
debug = true

[[bench]]
name = "basic"
harness = false
